### ISSUE TITLE
TypeGenerator regex pattern does not validate union return types

### ISSUE THREAD

**Issue by TheMechanicalButterfly** [laminas/laminas-code#66] opened 2020-12-30 08:32 UTC
When using class methods with PHP 8 union return types, an `InvalidArgumentException` is triggered.

Example processing the (simplified) method 
```
    public function getSomeValue(int $id): array|bool
    {
        return $this->orm->fetchValue($id); // Can return either the database result as an array or FALSE if no results are found.
    }
```
leads to the following error:
```
Details
Type: Laminas\Code\Generator\Exception\InvalidArgumentException
Code: 0
Message: Provided type "array|bool" is invalid: must conform "/^[a-zA-Z_\x80-\xff][a-zA-Z0-9_\x80-\xff]*(\\[a-zA-Z_\x80-\xff][a-zA-Z0-9_\x80-\xff]*)*$/"
File: D:\...\vendor\laminas\laminas-code\src\Generator\TypeGenerator.php
Line: 74
```

**Comment by Ocramius** [comment] 2020-12-30 09:51
Duplicate of #57.

**Closed as completed by Ocramius** 2020-12-30 09:51 UTC
Labels: Duplicate
