### ISSUE TITLE
Tag 4.5 to allow upper dependency on php8.1

### ISSUE THREAD

**Issue by jjsaunier** [laminas/laminas-code#117] opened 2021-12-02 16:49 UTC
Hello, 

I would like to upgrade in php 8.1, this library is an indirect dependency of doctrine migration via https://packagist.org/packages/friendsofphp/proxy-manager-lts and the latest stable is `4.4.x` which does not support 8.1. 

I would know if it's possible to tag a `4.5` which support it (https://github.com/laminas/laminas-code/commit/ba8865f5fad860bc7dc4fa30255a105b7314de31)

Cheers :v:

**Comment by Ocramius** [comment] 2021-12-02 17:55
See https://github.com/laminas/laminas-code/milestone/19

Duplicate of #116

**Closed as completed by Ocramius** 2021-12-02 17:55 UTC
Labels: Question

**Comment by jjsaunier** [comment] 2021-12-02 18:29
:+1: didn't see - prefer to wait then rather than tricking
